### ISSUE TITLE
/clanwarleagues/wars/{warTag} isn't avalible in api

### ISSUE THREAD

**Issue by AskoldMakaruk** [xRMG412/ClashOfClans.NET#1]
There is no way to retrieve war in league. Please add this, thanks

**Comment by rgret-dev** [comment]
I'm working on this now.

**Comment by rgret-dev** [comment]
I'll add the new version to nuget later today.

**Comment by rgret-dev** [comment]
Alright the new version has been pushed to nuget.

This version includes two new methods:
`GetCurrentLeagueGroupAsync(clanTag)`
`GetClanWarLeagueAsync(warTag)`
